### ISSUE TITLE
连点两次返回键退出有异常抛出(has leaked ServiceConnection null that was originally bound her)

### ISSUE THREAD

**Issue by tsuixl** [UnityTech/UIWidgets#212]
你好
      真机双击返回键退出会抛出异常, 如果有接入google服务,会导致第二次启动闪退,第三次启动才能正常进入游戏.
      下面是我新建的空测试场景.排除了自身sdk引发的可能.

运行环境
Unity 2018.4.0f1(Android)
compileSdkVersion 28
buildToolsVersion '28.0.3'

```
public class quiz_main : UIWidgetsPanel
    {
        protected override Widget createWidget()
        {
            return new WidgetsApp(
                home: new Container(
                    color: Colors.greenAccent
                    ),
                pageRouteBuilder: (settings, builder) => new PageRouteBuilder(settings: settings,
                    pageBuilder: (context, animation1, secondaryAnimation) => builder(context))
            );
        }
    }

```

com.Ts.Test E/ActivityThread: Activity com.unity3d.player.UnityPlayerActivity has leaked ServiceConnection null that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.unity3d.player.UnityPlayerActivity has leaked ServiceConnection null that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1525)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1417)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1599)
        at android.app.ContextImpl.bindService(ContextImpl.java:1551)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:688)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
        at android.os.MessageQueue.next(MessageQueue.java:400)
        at android.os.Looper.loop(Looper.java:149)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)

**Comment by kgdev** [comment]
好的多谢 我们会看一下

**Comment by tsuixl** [comment]
这个在有google服务框架下才会出现. 是Unity本身的问题, 使用Appliction.Quit()会出现该问题. 
只能等2018.4LTS修复或者升级2019 了
