### ISSUE TITLE
Android - Didn't find class "com.unity.uiwidgets.plugin.UIWidgetsMessageManager"

### ISSUE THREAD

**Issue by snksos** [UnityTech/UIWidgets#437]
unity2019.4.2f1 现在仅仅有gradle打包方式，但依旧还是会抱着个错误，需要在哪里设置吗？

现在的方式是：unity -> file -> build setting -> android -> export
然后去 android studio 运行项目，

下面报错信息：Loop

```
2020-08-12 00:01:34.860 17574-17658/com.nx.av E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.unity.uiwidgets.plugin.UIWidgetsMessageManager
    java.lang.ClassNotFoundException: com.unity.uiwidgets.plugin.UIWidgetsMessageManager
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$600(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$f$1.handleMessage(Unknown Source:150)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:213)
        at com.unity3d.player.UnityPlayer$f.run(Unknown Source:20)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.unity.uiwidgets.plugin.UIWidgetsMessageManager" on path: DexPathList[[zip file "/data/app/com.nx.av-L54JmIV-zxigNbDiSjyZhA==/base.apk"],nativeLibraryDirectories=[/data/app/com.nx.av-L54JmIV-zxigNbDiSjyZhA==/lib/arm64, /data/app/com.nx.av-L54JmIV-zxigNbDiSjyZhA==/base.apk
```

**Comment by snksos** [comment]
缺少了依赖
```
 cd <YourProjectPath>/Packages
 git clone https://github.com/UnityTech/UIWidgets.git com.unity.uiwidgets
```
